FROM node:20-alpine
WORKDIR /app

RUN addgroup -S mercari && adduser -S trainee -G mercari

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY src/ ./src/
COPY public/ ./public/
COPY tsconfig.json .

RUN chown -R trainee:mercari /app
USER trainee

CMD ["npm", "start"]
